// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.DataAccess;

#nullable disable

namespace TodoList.DataAccess.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    [Migration("20231118171522_add foriegn key to the todos table")]
    partial class addforiegnkeytothetodostable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("TodoList.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "blaaaa1",
                            Status = 1,
                            Tittle = "Do assignments",
                            UserEmail = "kvsumeshakalanka@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Description = "blaaaa2",
                            Status = 0,
                            Tittle = "Do execices",
                            UserEmail = "kvsumeshakalanka@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            Description = "blaaaa3",
                            Status = 0,
                            Tittle = "Do busness",
                            UserEmail = "kvsudeshanuradha@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            Description = "blaaaa4",
                            Status = 1,
                            Tittle = "Go to weding",
                            UserEmail = "kvsudeshanuradha@gmail.com"
                        });
                });

            modelBuilder.Entity("TodoList.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Email = "kvsumeshakalanka@gmail.com",
                            FirstName = "Sumesh",
                            LastName = "Akalanka",
                            Password = "123"
                        },
                        new
                        {
                            Email = "kvsudeshanuradha@gmail.com",
                            FirstName = "Sudesh",
                            LastName = "Anuradha",
                            Password = "123"
                        },
                        new
                        {
                            Email = "kvmeghathilini@gmail.com",
                            FirstName = "Megha",
                            LastName = "Thilini",
                            Password = "123"
                        },
                        new
                        {
                            Email = "kvmedhathisari@gmail.com",
                            FirstName = "Medha",
                            LastName = "Thisari",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("TodoList.Models.Todo", b =>
                {
                    b.HasOne("TodoList.Models.User", "User")
                        .WithMany("Todos")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoList.Models.User", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
